# Install HTTPD on CentOS
-   hosts: dev
    remote_user: ansible
    become: yes
    become_method: sudo
    connection: ssh
    gather_facts: yes
    vars: 
      username: myuser
    tasks:
    - name: Install HTTPS server of nodes
      yum: 
        name: httpd
        state: absent
      register: result
      notify:
      - startservice
    handlers:
    - name: startservice
      service:
        name: httpd
        state: restarted
    debug: var=result
