- hosts: dev
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars_files: 
  - vars.yaml
  tasks:
  - name: Install Lynx on App Servers
    yum: 
      name: lynx
      state: absent